import { useMemo, useState } from "react";
import { ArrowRight, CalendarPlus, CheckCircle2, Clock3, Dumbbell, Footprints, Shield, Sparkles } from "lucide-react";
import { MENEUR_DAYS, MENEUR_TECHNIQUE_BLOCKS, type MeneurDayKey, type MeneurPlannedSession } from "../../data/meneur-program";

const TYPE_META = {
  strength: { label: "Préparation physique", icon: Dumbbell, tone: "text-orange-300 bg-orange-400/10" },
  basket: { label: "Basket / équipe", icon: Shield, tone: "text-sky-300 bg-sky-400/10" },
  legday: { label: "Jambes & explosivité", icon: Footprints, tone: "text-emerald-300 bg-emerald-400/10" },
};

export function MeneurProgramLibrary({ onAddToPlanner }: { onAddToPlanner?: (day: MeneurDayKey, session: MeneurPlannedSession) => void }) {
  const [selectedDay, setSelectedDay] = useState<MeneurDayKey>("lundi");
  const program = useMemo(() => MENEUR_DAYS.find((day) => day.key === selectedDay) ?? MENEUR_DAYS[0], [selectedDay]);
  const meta = TYPE_META[program.type];
  const Icon = meta.icon;

  return (
    <section className="space-y-6">
      <header><p className="text-xs font-black uppercase tracking-[0.2em] text-orange-300/70">Programme fondateur</p><h2 className="mt-2 text-2xl font-black tracking-[-0.05em] text-white sm:text-3xl">Le Meneur Complet.</h2><p className="mt-2 max-w-2xl text-sm leading-relaxed text-slate-400">La base originale est conservée : préparation physique, tir, dribble, lecture, défense et récupération, organisés autour de ta semaine réelle.</p></header>

      <div className="flex gap-2 overflow-x-auto pb-1" role="tablist" aria-label="Jours du programme"><div className="flex min-w-max gap-2">{MENEUR_DAYS.map((day, index) => <button key={day.key} role="tab" aria-selected={selectedDay === day.key} onClick={() => setSelectedDay(day.key)} className={`rounded-xl border px-3 py-2 text-left transition ${selectedDay === day.key ? "border-orange-400/40 bg-orange-500/15 text-orange-100 shadow-lg shadow-orange-950/10" : "border-white/10 bg-slate-900/60 text-slate-500 hover:text-slate-200"}`}><span className="block text-[9px] font-black uppercase tracking-[0.15em] opacity-60">J{index + 1}</span><span className="mt-0.5 block text-xs font-bold">{day.label}</span></button>)}</div></div>

      <div className="grid gap-5 lg:grid-cols-[0.8fr_1.2fr]">
        <article className="rounded-[1.75rem] border border-orange-300/20 bg-gradient-to-br from-orange-500/15 via-slate-900/75 to-slate-950/70 p-5 shadow-2xl shadow-black/15 sm:p-6"><div className="flex items-start justify-between gap-3"><div className={`flex h-11 w-11 items-center justify-center rounded-2xl ${meta.tone}`}><Icon size={21} /></div><span className="rounded-full border border-white/10 bg-black/15 px-2.5 py-1 text-[10px] font-black uppercase tracking-[0.12em] text-slate-400">{meta.label}</span></div><h3 className="mt-5 text-xl font-black leading-tight text-white sm:text-2xl">{program.title}</h3>{program.technique && <p className="mt-3 rounded-xl border border-orange-300/10 bg-orange-500/5 px-3 py-2 text-xs font-bold text-orange-200">Technique : {program.technique}</p>}<div className="mt-6 grid grid-cols-2 gap-2"><div className="rounded-xl border border-white/5 bg-slate-950/40 p-3"><p className="text-[10px] font-black uppercase tracking-[0.14em] text-slate-600">Exercices</p><p className="mt-1 text-xl font-black text-white">{program.exercises.length || "—"}</p></div><div className="rounded-xl border border-white/5 bg-slate-950/40 p-3"><p className="text-[10px] font-black uppercase tracking-[0.14em] text-slate-600">Statut</p><p className="mt-1 flex items-center gap-1 text-sm font-black text-emerald-300"><CheckCircle2 size={15} /> Prêt</p></div></div><button onClick={() => onAddToPlanner?.(program.key, { id: `meneur-${program.key}`, title: program.title, source: "meneur-complet", exercises: program.exercises, technique: program.technique })} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-orange-500 to-amber-500 px-4 py-3 text-sm font-black text-white shadow-lg shadow-orange-950/20 transition hover:-translate-y-0.5"><CalendarPlus size={17} /> Ajouter au planning</button></article>

        <article className="rounded-[1.75rem] border border-white/10 bg-slate-900/65 p-4 shadow-xl shadow-black/10 sm:p-6"><div className="flex items-center justify-between"><div><p className="text-[10px] font-black uppercase tracking-[0.18em] text-slate-600">Séquence du jour</p><h3 className="mt-1 text-lg font-black text-white">Bloc physique</h3></div><Sparkles size={18} className="text-orange-300" /></div>{program.exercises.length ? <div className="mt-5 space-y-2">{program.exercises.map((exercise, index) => <div key={exercise.id} className="flex items-center gap-3 rounded-xl border border-white/5 bg-slate-950/40 p-3"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-lg bg-orange-500/10 text-xs font-black text-orange-300">{String(index + 1).padStart(2, "0")}</span><div className="min-w-0 flex-1"><p className="text-sm font-bold text-slate-200">{exercise.name}</p><p className="mt-0.5 text-xs text-slate-600">{exercise.prescription}</p></div><ArrowRight size={15} className="shrink-0 text-slate-700" /></div>)}</div> : <div className="mt-5 rounded-xl border border-dashed border-white/10 px-4 py-8 text-center"><Clock3 className="mx-auto text-sky-300" size={22} /><p className="mt-2 text-sm font-bold text-slate-300">Journée équipe / match</p><p className="mt-1 text-xs text-slate-600">Note la séance réalisée depuis le suivi.</p></div>}</article>
      </div>

      <article className="rounded-[1.75rem] border border-white/10 bg-slate-900/50 p-4 sm:p-6"><div className="flex items-center justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[0.18em] text-orange-300/70">Technique solo</p><h3 className="mt-1 text-xl font-black text-white">Les trois créneaux clés</h3></div><span className="rounded-full bg-orange-500/10 px-2.5 py-1 text-xs font-bold text-orange-200">Lundi · Mardi · Vendredi</span></div><div className="mt-5 grid gap-3 md:grid-cols-3">{MENEUR_TECHNIQUE_BLOCKS.map((block) => <div key={block.day} className="rounded-xl border border-white/5 bg-slate-950/40 p-4"><div className="flex items-center justify-between"><p className="text-sm font-black text-white">{block.day}</p><span className="text-[10px] font-bold text-orange-300">{block.badge}</span></div><p className="mt-1 text-xs font-bold text-slate-400">{block.title}</p><div className="mt-3 space-y-2">{block.blocks.map(([name, duration]) => <div key={name} className="flex items-center justify-between gap-2 text-xs"><span className="text-slate-500">{name}</span><span className="shrink-0 font-bold text-slate-300">{duration}</span></div>)}</div></div>)}</div></article>
    </section>
  );
}
